name: Build, Prerender & Deploy to Vercel (Verbose)

on:
  push:
    branches:
      - main  # change if necessary

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI: "true"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js (18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Show Node and NPM versions
        run: |
          node -v
          npm -v
          npm ci --version

      - name: Install dependencies (verbose)
        run: |
          set -x
          npm ci

      - name: Print environment (sensitive vars redacted)
        run: |
          echo "VERCEL_TOKEN present? $( [[ -n "${{ secrets.VERCEL_TOKEN }}" ]] && echo yes || echo no )"
          echo "VERCEL_ORG_ID present? $( [[ -n "${{ secrets.VERCEL_ORG_ID }}" ]] && echo yes || echo no )"
          echo "VERCEL_PROJECT_ID present? $( [[ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]] && echo yes || echo no )"
          echo "Listing repo root:"
          ls -la

      - name: Build (react-scripts build; react-snap runs in postbuild)
        run: |
          set -x
          npm run build
        env:
          NODE_ENV: production
          # add any required REACT_APP_* values here, e.g.
          # REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Check build folder contents
        run: |
          set -x
          echo "Build exists?"; test -d build && echo "yes" || (echo "build folder missing" && exit 1)
          ls -la build | sed -n '1,200p'
          echo "Show beginning of index.html"
          head -n 60 build/index.html || true

      - name: Install Vercel CLI
        run: |
          set -x
          npm install -g vercel@28

      - name: Deploy prebuilt static folder to Vercel (production)
        env:
          VERCEL_TOKEN: "80OXw7M5zDK8E53j0sf88Mih"
          # Optional:
          # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -x
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN missing. Aborting."
            exit 1
          fi
          # dry-run first for safety (uncomment if debugging)
          # vercel --prebuilt --token $VERCEL_TOKEN --confirm ./build
          vercel --prod ./build --confirm --token $VERCEL_TOKEN
