name: Build, Prerender & Deploy to Vercel (Stable)

on:
  push:
    branches:
      - main  # change if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install system Chromium & libs (for puppeteer)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
            libdrm2 libxkbcommon0 libxrandr2 libxss1 libasound2 libgbm1 libpangocairo-1.0-0 libxcomposite1 \
            libxdamage1 libxcb1 libx11-xcb1
          which chromium-browser || which chromium || true
          chromium-browser --version || chromium --version || true

      - name: Build (react-scripts build)
        env:
          NODE_ENV: production
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: |
          set -x
          npm run build

      - name: Run react-snap (explicit, with wait and timeout)
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: |
          set -x
          npx react-snap --source build --puppeteerTimeout=60000 --waitFor="#root" --crawl=false --include "/, /about, /about/vision-and-values, /about/milestone-and-recognitions, /about/innovation, /about/quality, /responsibility, /responsibility/csr, /responsibility/sustainability, /responsibility/ehs, /responsibility/uplifting-ecosystem, /products, /products/api, /products/intermediary, /manufacturing, /worldwide"

      - name: Sanity: show build contents
        run: |
          test -d build || (echo "build missing" && exit 1)
          ls -la build | sed -n '1,200p'
          head -n 60 build/index.html || true

      - name: Install Vercel CLI
        run: npm install -g vercel@28

      - name: Deploy prebuilt static folder to Vercel
        env:
          VERCEL_TOKEN: "80OXw7M5zDK8E53j0sf88Mih"
        run: |
          set -x
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN missing. Aborting."
            exit 1
          fi
          # deploy the prebuilt build folder (avoid Vercel building on their side)
          npx vercel@latest --prod --prebuilt ./build --token "$VERCEL_TOKEN"
